language: java

jdk:
- oraclejdk8

before_install:
- echo "Adding dependencies"
- chmod +x .travis/add_dependencies.sh
- .travis/add_dependencies.sh


script: 
- echo "Starting the build"
- gradle --stacktrace check compileJava compileTestJava 

